### ISSUE TITLE
[Bug] rqt 명령어 정상 실행 x

### ISSUE THREAD

**Issue by SKKUJoseph** [Jinsun-Lee/ROS2-template#11]
# 무슨 에러 내용인지 한국어로 설명 
아래 명령어 입력시, 가제보 실행 이상 x, 차량 동작 이상 x, rqt 정상 실행이 안되는 것 처럼 보임

```
[gazebo-1] [Err] [InsertModelWidget.cc:403] Missing model.config for model "/home/joseph/.gazebo/models/etc"
[gazebo-1] [INFO] [1729682299.462528447] [camera_controller]: Publishing camera info to [/upper_camera/camera_info]
[debug_node-6] [INFO] [1729682299.499818307] [debug_node]: Debug node created
[debug_node-6] [INFO] [1729682299.500355900] [debug_node]: Configuring debug_node
[yolov8_node-5] [INFO] [1729682299.501986900] [yolov8_node]: Yolov8Node created
[yolov8_node-5] [INFO] [1729682299.502495883] [yolov8_node]: Configuring yolov8_node

```

이미지
![Screenshot from 2024-10-23 20-19-19](https://github.com/user-attachments/assets/7248cdff-7c2b-40df-9b85-a92967b13de0)
![Screenshot from 2024-10-23 20-19-33](https://github.com/user-attachments/assets/f463b3c6-e774-43db-9452-31b6db90a609)

**Comment by Jinsun-Lee** [comment]
### `1. 주행 환경 시뮬레이션1` 영상 `1:03`에서 설명합니다
![image](https://github.com/user-attachments/assets/8e1001e8-5319-4537-9bcf-9e05d412787f)
