### ISSUE TITLE
[Bug] 05. 초기설정의 모델을 경로에 맞게 복사하는 부분이 동작하지 않음

### ISSUE THREAD

**Issue by choi-minkwon** [Jinsun-Lee/ROS2-template#12]
![스크린샷 2024-10-25 13-11-17](https://github.com/user-attachments/assets/96ec40fa-2d32-4121-b4db-e33c74a14786)

우측에 보이는 인터넷 설명서대로 모델을 복사하려고 했는데, 화면과 같은 에러가 뜹니다

**Comment by Jinsun-Lee** [comment]
1. 폴더를 열고
2. 좌측 탐색기에서 홈을 클릭
3. crtrl + h를 누르고
4. 사진을 캡처해서 첨부해 주세요

**Comment by choi-minkwon** [comment]
![스크린샷 2024-10-25 13-11-42](https://github.com/user-attachments/assets/d6f659fe-477b-40fe-a6c2-f7016417c3d9)

**Comment by Jinsun-Lee** [comment]
1. ROS2 개발 환경 설정을 하시고
2. 1.1의 명령어를 실행하신 다음
3. 다시 똑같은 경로의 화면을 캡처해 주세요

**Comment by choi-minkwon** [comment]
![image](https://github.com/user-attachments/assets/3d7514e5-85c8-48be-aebe-07dae6ab45b3)

```
cd ~/ros2_ws
source /opt/ros/humble/setup.bash
source install/local_setup.bash

ros2 launch self_driving_car_pkg car_sim.launch.py 
```
위 명령어를 실행했는데 제대로 gazebo 프로그램이 실행되지 않아서 종료했습니다

**Comment by Jinsun-Lee** [comment]
기존에는 없던 .gazebo 폴더가 생긴 것을 확인할 수 있습니다

폴더에 들어가서 models 폴더가 있는지 확인해 주세요

없다면 models라는 이름의 새 폴더를 생성하시고, 05번부터 다시 진행하시면 됩니다

**Comment by choi-minkwon** [comment]
![image](https://github.com/user-attachments/assets/92d60fb7-d2bb-42f4-bb92-3ea2c8721b30)

models 폴더가 없어서 생성하고 다시 진행하니 다시 동작합니다.
