### ISSUE TITLE
[Bug] 터미널에서 MOVE 명령을 실행할 수 없습니다.

### ISSUE THREAD

**Issue by choi-minkwon** [Jinsun-Lee/ROS2-template#13]
![image](https://github.com/user-attachments/assets/06e67154-fc2d-4b5d-9171-fcdd0f439005)

1.1 주행 launch 실행 명령어를 입력하여 gazebo를 실행한 후,  '1. 주행 환경 시뮬레이션1' 동영상 3:01 에 나오는 내용을 따라 MOVE 명령을 입력했을 때 위와 같은 메세지와 함께 MOVE 명령을 실행 시킬 수 없었습니다.

**Comment by Jinsun-Lee** [comment]
![Screenshot_20241025_165244_GitHub.jpg](https://github.com/user-attachments/assets/aba52a62-8f2b-4eaa-8a19-174474a277b7)

config.py 파일에서 아래처럼 수정해 주세요


= "cpu" # "cuda:0" # "cpu"

**Comment by choi-minkwon** [comment]
![image](https://github.com/user-attachments/assets/0025fd23-1a73-419e-8d00-4a419771676e)

ros_ws2 폴더에서 config.py 파일을 검색하였더니 2개의 파일이 검색되었습니다. 2개 중 어떤 config.py를 수정하면 될까요?

**Comment by Jinsun-Lee** [comment]
@choi-minkwon src 경로의 파일을 수저이하시면 됩니다

**Comment by choi-minkwon** [comment]
![image](https://github.com/user-attachments/assets/a2607a80-900a-4597-9c8c-e197b4398a91)

yolov8_instance_segmentation_model_device = "cpu" # "cuda:0" # "cpu"

위의 코드를 넣어도 동작되지 않았으나 새로 연 창에서 1.주행 환경 시뮬레이션의 'ROS2 개발 환경 설정' 코드를 넣었을 때 동작되는 것을 확인하였습니다.

**Comment by Jinsun-Lee** [comment]
MOVE를 실행하는 터미널에서 아래 명령어를 실행했더니 제대로 동작하죠?

⭐ ROS2 개발 환경 설정 
```
cd ~/ros2_ws
source /opt/ros/humble/setup.bash
source install/local_setup.bash
```

**Comment by choi-minkwon** [comment]
넵
